language: cpp

os:
  - osx
  - linux

osx_image: xcode8.3
dist: trusty
sudo: false

compiler:
  - gcc
  - clang

install:
  - mkdir build
  - cd build
  - cmake ..
  - pip install wheel

script:
  - pwd
  - make VERBOSE=1

after_success:
  - cd ${TRAVIS_BUILD_DIR}/python
  - python setup-pip.py bdist_wheel

addons:
  artifacts: true

addons:
  artifacts:
    s3_region: "us-west-1"  # NorCal
    paths:
    - $(git ls-files -o | egrep '.whl$' | tr "\n" ":")
